use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::convention::{FlushEngine, FlushRequest, FlushResult};
use crate::distill::extractor::SkillExtractor;
use crate::distill::model::DistilledSkill;
use crate::offload::inspect_node;

/// Options for parameterizing the distillation of traces into a skill card.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DistillOptions {
    /// Explicit skill title (auto-generated by SkillExtractor if omitted).
    pub title: Option<String>,
    /// Optional context or prompt explanation for the trace.
    pub context_hint: Option<String>,
    /// Target category (defaults to "skill").
    pub category: Option<String>,
    /// Optional extra tags.
    pub tags: Vec<String>,
    /// Optional related note titles or WikiLinks.
    pub related_notes: Vec<String>,
    /// Preview only, do not write to vault.
    pub dry_run: bool,
}

/// Result of distilling an execution trace into a crystallized skill.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DistillResult {
    /// The structured distilled skill model.
    pub skill: DistilledSkill,
    /// Result from the safe flush operation.
    pub flush_result: FlushResult,
    /// Full synthesized Markdown content.
    pub preview_markdown: String,
}

/// The core distillation engine bridging raw traces and crystallized vault skills.
pub struct DistillEngine {
    vault_root: PathBuf,
    refs_dir: PathBuf,
}

impl DistillEngine {
    /// Create a new DistillEngine targeting a vault root and offloaded references directory.
    pub fn new(vault_root: impl Into<PathBuf>, refs_dir: impl Into<PathBuf>) -> Self {
        Self {
            vault_root: vault_root.into(),
            refs_dir: refs_dir.into(),
        }
    }

    /// Set a custom vault root directory.
    pub fn with_vault_root(mut self, vault_root: impl Into<PathBuf>) -> Self {
        self.vault_root = vault_root.into();
        self
    }

    /// Set a custom references directory.
    pub fn with_refs_dir(mut self, refs_dir: impl Into<PathBuf>) -> Self {
        self.refs_dir = refs_dir.into();
        self
    }

    /// Distill a raw in-memory trace string into a skill card and flush to the vault.
    pub fn distill_text(
        &self,
        raw_trace: &str,
        opts: DistillOptions,
    ) -> Result<DistillResult, Box<dyn std::error::Error + Send + Sync>> {
        // 1. Extract structured skill using heuristic analyzer
        let mut skill = SkillExtractor::extract(
            raw_trace,
            opts.context_hint.as_deref(),
            opts.title.as_deref(),
        );

        // Merge any user-specified tags
        for tag in opts.tags {
            let clean = tag.trim().to_string();
            if !clean.is_empty() && !skill.tags.contains(&clean) {
                skill.tags.push(clean);
            }
        }

        // Merge any user-specified related notes
        for note in opts.related_notes {
            let clean = note.trim().to_string();
            if !clean.is_empty() && !skill.related_notes.contains(&clean) {
                skill.related_notes.push(clean);
            }
        }

        // 2. Synthesize markdown representation
        let markdown = skill.to_markdown();

        // 3. Delegate to FlushEngine for safe write-back and auto-indexing
        let flush_engine = FlushEngine::new(&self.vault_root)?;
        let category = opts.category.unwrap_or_else(|| "skill".to_string());

        let flush_req = FlushRequest {
            title: skill.title.clone(),
            summary: Some(format!("Distilled skill: {}", skill.title)),
            content: markdown.clone(),
            category,
            tags: skill.tags.clone(),
            related_notes: skill.related_notes.clone(),
            dry_run: opts.dry_run,
        };

        let flush_result = flush_engine.flush(flush_req)?;

        Ok(DistillResult {
            skill,
            flush_result,
            preview_markdown: markdown,
        })
    }

    /// Distill a skill from an offloaded node identifier in the refs directory.
    pub fn distill_node(
        &self,
        node_id: &str,
        opts: DistillOptions,
    ) -> Result<DistillResult, Box<dyn std::error::Error + Send + Sync>> {
        let raw_trace = inspect_node(&self.refs_dir, node_id)
            .map_err(|e| format!("Failed to read log node '{}': {}", node_id, e))?;
        self.distill_text(&raw_trace, opts)
    }

    /// Distill a skill from a log file path on disk.
    pub fn distill_file(
        &self,
        path: &Path,
        opts: DistillOptions,
    ) -> Result<DistillResult, Box<dyn std::error::Error + Send + Sync>> {
        if !path.exists() {
            return Err(format!("Trace file not found: {}", path.display()).into());
        }
        let raw_trace = fs::read_to_string(path)?;
        self.distill_text(&raw_trace, opts)
    }
}
